//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NapolniBazo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Podatkis
    {
        public int Id { get; set; }
        public int IdPostaje { get; set; }
        public System.DateTime Cas { get; set; }
        public decimal Temp { get; set; }
        public decimal Vlaga { get; set; }
        public string Nekaj { get; set; }
        public string Nevem { get; set; }
        public decimal Padavine { get; set; }
    }
}
